services:
  kauppie-service1:
    build: "./service1"
    networks:
      - kauppie-skynet
    volumes:
      - "./logs:/app/logs"
    environment:
      # Specify name of service 2 for resolving its address.
      - "SERVICE2=kauppie-service2"

  kauppie-service2:
    build: "./service2"
    networks:
      - kauppie-skynet
    volumes:
      - "./logs:/app/logs"

networks:
  kauppie-skynet:
    driver: bridge
