services:
  kauppie-service1:
    build: "./service1"
    networks:
      - kauppie-skynet
    environment:
      # Specify name of service 2 for resolving its address.
      - "SERVICE2=kauppie-service2"
      - "RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - kauppie-rabbitmq

  kauppie-service2:
    build: "./service2"
    networks:
      - kauppie-skynet
    depends_on:
      - kauppie-rabbitmq

  kauppie-monitor:
    build: "./monitor"
    hostname: kauppie-monitor
    networks:
      - kauppie-skynet
    environment:
      - "RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - kauppie-rabbitmq
    ports:
      - "8087:8087"

  kauppie-rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    networks:
      - kauppie-skynet
    ports:
      - "15672:15672"

networks:
  kauppie-skynet:
    driver: bridge
